captainVersion: 4

services:
    '$$cap_appname':
        image: index.docker.io/openspeedtest/latest:$$cap_openspeedtest_version
        caproverExtra:
            containerHttpPort: '3000'
        restart: always

caproverOneClickApp:
    variables:
        - id: '$$cap_openspeedtest_version'
          label: OpenSpeedTest Version
          defaultValue: 'v2.0.5'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/openspeedtest/latest/tags
    instructions:
        start: |-
            OpenSpeedTest is a self-hosted speedtest. You can read more about this on https://openspeedtest.com/selfhosted-speedtest.
        end: |-
            OpenSpeedTest has been successfully deployed!

            Enabling `https` under the app settings is recommended.

            **Note**: If you find your results are not accurate, refer to https://github.com/openspeedtest/Speed-Test/issues/4. You may need to adjust the default Nginx configuration in the app's settings (be **careful** when editing your app's Nginx configuration) to disable `http2` and/or adjust the `client_max_body_size`. For more information, see https://github.com/openspeedtest/Nginx-Configuration/blob/f452c9b25bd28b29f9d23b28b6c1ce709bcfde6c/OpenSpeedTest-Server.conf
    displayName: OpenSpeedTest
    isOfficial: true
    description: |-
        OpenSpeedTest is a self-hosted network speedtest written in vanilla Javascript.
